spring.application.name=app

# MySQL datasource (local)
# Create a database first: `CREATE DATABASE oros_app;`
spring.datasource.url=jdbc:mysql://localhost:3306/oros_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=zackDigits
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# JWT settings
jwt.secret=change_this_secret_change_this_secret_change
jwt.expiration=86400000
